title: ANL501 Data Visualisation and Storytelling
theme: jekyll-theme-minimal 
logo: dengue.png
description: "_A most gruesome and nerve-racking assignment to finish as my last module with SUSS in exchange for the master's certificate_"  (Anonymous) 


